# coding: utf-8

"""
    Clever Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.term import Term  # noqa: E501
from swagger_client.rest import ApiException


class TestTerm(unittest.TestCase):
    """Term unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTerm(self):
        """Test Term"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.term.Term()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
