# Python package
# Create and test a Python package.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines wheel twine
    pytest
  displayName: 'pytest'
- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'Strongmind/StrongMindPackages'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'setup.py'
    arguments: 'sdist bdist_wheel'
- script: |
   twine upload -r StrongMindPackages --config-file $(PYPIRC_PATH) dist/*
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main') # only push to artifacts when PR is completed
  displayName: 'upload to artifacts'