# coding: utf-8

# flake8: noqa

"""
    Clever Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.courses_api import CoursesApi
from swagger_client.api.districts_api import DistrictsApi
from swagger_client.api.events_api import EventsApi
from swagger_client.api.resources_api import ResourcesApi
from swagger_client.api.schools_api import SchoolsApi
from swagger_client.api.sections_api import SectionsApi
from swagger_client.api.terms_api import TermsApi
from swagger_client.api.users_api import UsersApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.bad_request import BadRequest
from swagger_client.models.contact import Contact
from swagger_client.models.course import Course
from swagger_client.models.course_object import CourseObject
from swagger_client.models.course_response import CourseResponse
from swagger_client.models.courses_created import CoursesCreated
from swagger_client.models.courses_deleted import CoursesDeleted
from swagger_client.models.courses_response import CoursesResponse
from swagger_client.models.courses_updated import CoursesUpdated
from swagger_client.models.credentials import Credentials
from swagger_client.models.district import District
from swagger_client.models.district_admin import DistrictAdmin
from swagger_client.models.district_contact import DistrictContact
from swagger_client.models.district_object import DistrictObject
from swagger_client.models.district_response import DistrictResponse
from swagger_client.models.districts_created import DistrictsCreated
from swagger_client.models.districts_deleted import DistrictsDeleted
from swagger_client.models.districts_response import DistrictsResponse
from swagger_client.models.districts_updated import DistrictsUpdated
from swagger_client.models.event import Event
from swagger_client.models.event_response import EventResponse
from swagger_client.models.events_response import EventsResponse
from swagger_client.models.internal_error import InternalError
from swagger_client.models.link import Link
from swagger_client.models.location import Location
from swagger_client.models.name import Name
from swagger_client.models.not_found import NotFound
from swagger_client.models.principal import Principal
from swagger_client.models.resource import Resource
from swagger_client.models.resource_object import ResourceObject
from swagger_client.models.resource_response import ResourceResponse
from swagger_client.models.resources_created import ResourcesCreated
from swagger_client.models.resources_deleted import ResourcesDeleted
from swagger_client.models.resources_response import ResourcesResponse
from swagger_client.models.resources_updated import ResourcesUpdated
from swagger_client.models.roles import Roles
from swagger_client.models.school import School
from swagger_client.models.school_enrollment import SchoolEnrollment
from swagger_client.models.school_object import SchoolObject
from swagger_client.models.school_response import SchoolResponse
from swagger_client.models.schools_created import SchoolsCreated
from swagger_client.models.schools_deleted import SchoolsDeleted
from swagger_client.models.schools_response import SchoolsResponse
from swagger_client.models.schools_updated import SchoolsUpdated
from swagger_client.models.section import Section
from swagger_client.models.section_object import SectionObject
from swagger_client.models.section_response import SectionResponse
from swagger_client.models.sections_created import SectionsCreated
from swagger_client.models.sections_deleted import SectionsDeleted
from swagger_client.models.sections_response import SectionsResponse
from swagger_client.models.sections_updated import SectionsUpdated
from swagger_client.models.staff import Staff
from swagger_client.models.student import Student
from swagger_client.models.student_relationship import StudentRelationship
from swagger_client.models.teacher import Teacher
from swagger_client.models.term import Term
from swagger_client.models.term_object import TermObject
from swagger_client.models.term_response import TermResponse
from swagger_client.models.terms_created import TermsCreated
from swagger_client.models.terms_deleted import TermsDeleted
from swagger_client.models.terms_response import TermsResponse
from swagger_client.models.terms_updated import TermsUpdated
from swagger_client.models.user import User
from swagger_client.models.user_object import UserObject
from swagger_client.models.user_response import UserResponse
from swagger_client.models.users_created import UsersCreated
from swagger_client.models.users_deleted import UsersDeleted
from swagger_client.models.users_response import UsersResponse
from swagger_client.models.users_updated import UsersUpdated
