name: Python Build

on: 
  push:
    branches:
      - main

jobs:
  build-package:
    uses: Strongmind/public-reusable-workflows/.github/workflows/python-package-build.yml@main
    secrets: inherit
